### ISSUE TITLE
Cascading-Picklist Not Working with New Boards Hubs

### ISSUE THREAD

**Issue by palencharj** [microsoft/azure-devops-extension-cascading-picklist#107]
In side of ADO while one has the New Boards Hubs Preview feature enabled cascading picklist will not work.
By this I mean that it will not filter the work item

**Comment by cbakerfcbt** [comment]
We have the same experience. With the new Boards Hubs preview feature enabled the cascading picklist options aren't working. If we disable the preview feature, the cascading lists work as expected again.

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by hustold** [comment]
Experiencing same issue here.  When will this be fixed?

**Comment by AminTi** [comment]
Hi!,  the issue you reported earlier has been resolved. Thank you for bringing this to our attention and helping us improve our service, If you have any further questions or concerns, please do not hesitate to reach out to us.
