### ISSUE TITLE
Delay in refreshing the 2nd picklist

### ISSUE THREAD

**Issue by automagicallyio** [microsoft/azure-devops-extension-cascading-picklist#110]
Hello,

I am using your Cascading list extension (thank you, btw) and noticed that there is a delay when updating 2nd list from the cascading list. Here is scenario:

1. Select Value1 from List1
2. List2 shows all values instead just showing values associated with Value1 from List1
3. Then, I select any value from List2
4. Click on some other field on the form
5. Then, go back to List2 picklist and now I see only  values associated with Value1 from List1 as expected

Is this by design? Is there a way to avoid this delay and extra click? I got no other extensions installed in the org except for this extension.

**Comment by AminTi** [comment]
If you're still experiencing the same problem, let's schedule a web session
