### ISSUE TITLE
How to create two separate picklist for 2 work items (feature and task).

### ISSUE THREAD

**Issue by ITSNadySedky** [microsoft/azure-devops-extension-cascading-picklist#111]
I have created Picklist on Feature work item (Product ,Release) its working fine but when I created anther Picklist (Task type, Component) on Task Work Item  not working and also I don't know how to edit config file to add separate picklist for 2 work items

**Comment by AminTi** [comment]
Hi! @ITSNadySedky , For now, it's not doable.
