### ISSUE TITLE
With the new update of ADO, this extension does not seem to work anymore

### ISSUE THREAD

**Issue by jmlesfrite** [microsoft/azure-devops-extension-cascading-picklist#119]
Like title states, the new update seems to break the extension. Do you think you could have a look? Ty!

**Comment by AminTi** [comment]
Hi, Could you please provide more details about what specifically is causing the problem? If you can provide more information, I'd be happy to assist. Thank you!

**Comment by AminTi** [comment]
![Screenshot 2023-10-12 at 12 58 42](https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/54841342/7847b46c-9c75-4206-863d-3027c752a820)

**Comment by AminTi** [comment]
I just tested it, and it's working as expected. Please let me know when you're available for a web session so I can assist you with any questions or issues.
