### ISSUE TITLE
Enabling Preview of New Board Hubs results in cascading list not working

### ISSUE THREAD

**Issue by ssteiner1** [microsoft/azure-devops-extension-cascading-picklist#121]
Hello there,

When New Board Hub preview is enabled in Chrome, Version 118.0.5993.89 (Official Build) (64-bit) the cascade list functionality does not work.  I know there was a previous submission on this that was closed.  I am available to demonstrate after 11/2 (due to taking holiday).

**Comment by AminTi** [comment]
Hello, I tested it the last time, and it worked as expected. I will test it again and inform you of the results.

**Comment by ssteiner1** [comment]
Yes, I saw that closed submission.  I am happy to demonstrate to you if necessary.  We use cascading lists in every project.  New functionality is available under the board preview that our teams have been requesting.  So if we can get both to be in harmony it would be awesome.  Thanks!

**Comment by AminTi** [comment]
Hi, do u have time tomorrow ? 11:00 CET

**Comment by AminTi** [comment]
amin.titi@solidify.dev

**Comment by dominikbohm** [comment]
Hi, it works only partially. If you select from the top picklist (tree node 1), the cascaded picklist (tree node 2) shows the correct items. However, if you then change the top picklist value, the linked picklist does not refresh, it is empty. You have to close the workitem, refresh the whole page, open the workitem again to make it work again (for one shot).

**Comment by ssteiner1** [comment]
@AminTi My org does not allow us to add external users.  We can schedule a teams meeting however, please let me know your availability.  I am US based, EST.

**Comment by dominikbohm** [comment]
@Tanmay545 Unfortunately not :-(

**Comment by Febiunz** [comment]
I am facing the same issue. That is: it all seems to be working fine with the New Boards Hub preview feature turned ON when opening Test Cases with cascading dropdowns from for example a query result view. But when I open a Test Case in the 'popup' view from example a Test Suite, double click on the Test Case, it is NOT working. When I turn of the New Boards Hub preview feature the 'popup' view is working fine also. So it has something to do with the new Boards Hub.

**Comment by MOlausson** [comment]
All, I've re-ran tests on version 0.1.24, both for a Feature and a Test Case using the example in the extension docs. All works as expected on both old and New Boards Hub.
@dominikbohm @Febiunz @ssteiner1 @Tanmay545 please check again and re-open the issue if you still have issues with the extension.

**Comment by Febiunz** [comment]
@MOlausson I can confirm that it works now! Thank you!

**Comment by dominikbohm** [comment]
@MOlausson I have the same version 0.1.24, but it was installed already on 6th November 2023. Nothing changed, the behavior is still the same. After I change the first level node, the second level list is empty. I have to refresh the browser to load the corresponding nodes on level 2.
