### ISSUE TITLE
Cascading list do not work

### ISSUE THREAD

**Issue by CStumpo** [microsoft/azure-devops-extension-cascading-picklist#127]
We are a bank and not a IT company and use Azure DevOps for project management.

We have serious problems of lack of technical skills and because of that ee do not know what to do for fixing the problem. 

Could you please can help me?

You answer my review on extension page, and sent me that link: https://github.com/microsoft/azure-devops-extension-cascading-picklist

You can see my review on link on right and my name is Carlos Stumpo (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.cascading-picklists-extension&ssr=false#review-details).

If you can keep in touch thru email I will be glad.

Thank you so much.

**Comment by AminTi** [comment]
I have just tested it, and it appears to be working as expected. Please reach out to me so that I can assist you further.  amin.titi@solidify.dev
