### ISSUE TITLE
After initial save of Cascading Lists Config - cannot change and save again

### ISSUE THREAD

**Issue by andrejusc** [microsoft/azure-devops-extension-cascading-picklist#130]
While following Readme - initially saved Cascading Lists Config as provided JSON. But later when trying to access it and change - it doesn't show me that page properly.

![image](https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/12596588/797641af-adb5-4d6f-be09-3f07a742c2b2)

If looking at Browser console - it presents such error at that point:
```
bootstrap:19 
 The AzureDevOps SDK is already loaded. Only one version of this module can be loaded in a given document.
(anonymous)	@	SDK.js:53
./node_modules/azure-devops-extension-api/node_modules/azure-devops-extension-sdk/SDK.js	@	SDK.js:302
__webpack_require__	@	bootstrap:19
./node_modules/azure-devops-extension-api/Common/Client.js	@	Client.js:1
__webpack_require__	@	bootstrap:19
./node_modules/azure-devops-extension-api/Common/index.js	@	index.js:1
__webpack_require__	@	bootstrap:19
./src/common/cascading.service.ts	@	cascading.service.ts:1
__webpack_require__	@	bootstrap:19
./src/common/manifest.service.ts	@	manifest.service.ts:3
__webpack_require__	@	bootstrap:19
./src/confighub/hooks/configstorage.ts	@	configstorage.ts:4
__webpack_require__	@	bootstrap:19
./src/confighub/views/ConfigView.tsx	@	ConfigView.tsx:5
__webpack_require__	@	bootstrap:19
./src/confighub/app.tsx	@	app.tsx:4
__webpack_require__	@	bootstrap:19
./src/confighub/index.tsx	@	index.tsx:5
__webpack_require__	@	bootstrap:19
(anonymous)	@	startup:4
(anonymous)	@	startup:4

```

Is this known issue/bug? Using currently v0.1.16 built from this repo

**Comment by AminTi** [comment]
Hello, I've tested it, and it's working as expected. Please check the documentation for more help. If you're still having trouble, let's set up a web session so I can assist you better.

**Comment by AminTi** [comment]
Hello, I'm going to close this issue. Please inform me if you require any further assistance.
