### ISSUE TITLE
Cascading list is not working even though we added new values, it shows saved configuration but once refresh all the values vanished

### ISSUE THREAD

**Issue by Hitaishi2** [microsoft/azure-devops-extension-cascading-picklist#135]
I need your quick assistance on Cascading list extension from Microsoft DevLabs, till yesterday it was working fine. Today morning when i checked, configured list is vanished and only empty version and cascade template is there. So i again created a list and saved it. It gives successfully saved message but after refresh again it takes to empty screen. We tried enable/disable the cascading extension, uninstall and reinstall also didnt work. We are using latest version only.
Please do the needful.
<img width="816" alt="cascading list is not working" src="https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/165376925/172eb1d8-aa26-485a-8834-335597bb40e2">

**Comment by ssteiner1** [comment]
We have the same issue in over 50 projects.

**Comment by akhurst** [comment]
We are having the same issue. It says it saved, but when you open it again, your changes aren't there. Same config worked before and the picklist fields themselves have not been touched.

**Comment by Skinner007** [comment]
We are seeing the same issue, and it looks to have started today. Edits to attempt to restore the configuration json fail. The extension shows a toast saying it has saved the configuration, but a refresh of the screen shows the default empty configuration. Since there have been no updates to the extension in the last 5 months, it would appear to be an ADO update that is causing the failure. Either way, the extension is effectively broken and non-functional due to the configuration json being lost and we are no longer able to save configurations.

**Comment by Hitaishi2** [comment]
Any update on the above raised issue please?

**Comment by Hitaishi2** [comment]
> I need your quick assistance on Cascading list extension from Microsoft DevLabs, till yesterday it was working fine. Today morning when i checked, configured list is vanished and only empty version and cascade template is there. So i again created a list and saved it. It gives successfully saved message but after refresh again it takes to empty screen. We tried enable/disable the cascading extension, uninstall and reinstall also didnt work. We are using latest version only. Please do the needful. <img alt="cascading list is not working" width="816" src="https://private-user-images.githubusercontent.com/165376925/318013024-172eb1d8-aa26-485a-8834-335597bb40e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjI3MTQsIm5iZiI6MTcxMTk2MjQxNCwicGF0aCI6Ii8xNjUzNzY5MjUvMzE4MDEzMDI0LTE3MmViMWQ4LWFhMjYtNDg1YS04ODM0LTMzNTU5N2JiNDBlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwOTA2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGVmMjA1MjZmY2MyYmZjZjlkOGY4ZjY4ZjhlODc4OWFhNTk5NDk3ZGEyZmMwMzAxZjcxY2I2ZGEwYTBmYzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fzOpxObiEG2C5euZ1PdGPpExm07AczsBWb0Tf-Xv6Qc">

Any update on this issue please?

**Comment by tarains** [comment]
We have this same issue. All of our Azure devops projects config files have been reset. Are these config files saved somewhere as a backup? Or do they need to be recreated. This will be a large effort to recreate. Is there a known issue? Are the config files recoverable?

**Comment by kclarey** [comment]
We have the same issue with our devops project configuration being reset.

**Comment by MOlausson** [comment]
Hi all, thanks for reporting. The extension hasn't been updated for a while so this must be related to the environment. We'll take a look and get back.

**Comment by MOlausson** [comment]
We've identified the problem, and a fix has been deployed so the extension should work fine again.

**Comment by MOlausson** [comment]
We take no feedback as it's all good now. Closing the issue but feel free to reopen if you're still having issues.

**Comment by aparnak799-v** [comment]
Hello,

We are facing this issue again. We have updated our Cascading List config with new values, but the values do not show up in the work items.

**Comment by AminTi** [comment]
Hi @aparnak799-v, after testing, it works as expected. Could you please share the console and network logs?

**Comment by MOlausson** [comment]
Adding to this thread - the latest issue was resolved by adding the desired items in the picklist so it matches the configuration.
