### ISSUE TITLE
Cascading List stops working with the preview feature "New Boards Hubs" enabled

### ISSUE THREAD

**Issue by melmalo** [microsoft/azure-devops-extension-cascading-picklist#138]
I've been using the cascading list extension for a number of years with no difficulty.  When I went to implement this in a new organization however, I was not able to get it to work initially.

The json file was accurate and did specify the exact name of the Custom.FieldName(s) and was saved and shown as valid.  When I went to test the cascading list though, the sub field did not get properly entered.  Example:

ParentField
SubField

{
  "version": "1",
  "cascades": {
    "Custom.ParentField": {
      "Option 1": {
        "Custom.SubField": [
          "General"
        ]
      },
      "Option 2": {
        "Custom.SubField": [
          "General"
        ]
      },
      "Option 3": {
        "Custom.SubField": [
          "General",
          "Not General"
        ]
      }
    }
  }
}

Obviously the json was fine.  Those fields were added to my work item with the exact name as specified above, but it didn't work.

I found out after a lot of investigation that the preview feature "New Boards Hubs" was enabled, and turning this off actually fixed my issue temporarily at least.  If this feature is introduced into ADO going forward, we will no longer have to option to disable it.  

Please investigate why this breaks the cascading lists please.

**Comment by ssteiner1** [comment]
Thank you for entering this.  I tried and my issue got closed because it can't be recreated and I am not allowed by our security team to screen record and send outside of our company to demo.  Hopefully someone will investigate this.

**Comment by AminTi** [comment]
I just tested it, and it worked as expected for me. Could you please describe your environment and provide screenshots of the console log and network?

**Comment by melmalo** [comment]
I am unable to provide screenshots of the console log and network.  The environment I am using is an SaaS solution in the cloud but located on Defense 365 and contains information that I am not able to give you access to.  

I can try and describe more info though for you to be able to reproduce.

1. Installed Cascading list extension
2. Created two custom fields that contained all values;  Field one containing Option 1, Option 2 and Option 3 and Field two containing General and Not General (Fictional data of course)
3. Configured .json file correctly as above (Saved, no errors)
4. Created new work item, and selected Option 1, this should just list general but listed both general and not general.
5. Attempted to modify an existing work item, same thing
6. Tried on Windows 10, Windows 11 on latest version of Edge, Chrome and FireFox, same results
7. Tried recreating the fields to ensure there was no spelling errors or anything else that would cause this
8. Repeated all steps above
9. Finally after googling for quite some time, I found a post that said to try to turn off "New Boards Hubs" from preview features.  As soon as I did this, the Cascading lists worked as expected.

If I have some time today, I will try to recreate in a sandbox environment with no security concerns and send you screenshots from the fictional data.  I'm not exactly sure how to send you console logs and information on a complete SaaS solution given it exists with Microsoft in the cloud.  If you can explain how that is done, I can attempt to do that from the sandbox environment also.

**Comment by AminTi** [comment]
Hi, I just tested it again, and it worked as expected. 

https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/54841342/e26c6bd2-ef4a-4e2c-939e-78db5924e2be

{
  "version": 1,
  "cascades": {
    "Custom.MajorRelease": {
      "Release Blue": {
        "Custom.MinorRelease": [
          "Blue.1",
          "Blue.2",
          "Blue.3"
        ]
      },
      "Release Red": {
        "Custom.MinorRelease": [
          "Red.A",
          "Red.B",
          "Red.C"
        ]
      },
      "Release Yellow": {
        "Custom.MinorRelease": [
          "Yellow.A",
          "Yellow.B",
          "Yellow.C"
        ]
      }
    }
  }
}

**Comment by melmalo** [comment]
@AminTi 
Did you have the specific preview feature disabled "New Boards Hubs" and are you working in the cloud because this definitely does not work in any environment for me factoring in those two things as previously described and demonstrated through the pictures and exact scenario I provided.  Your video capture does not show the Preview Features.

**Comment by AminTi** [comment]
Hi, as mentioned, it worked as expected. Please check that you made the correct configuration/field.
https://github.com/microsoft/azure-devops-extension-cascading-picklist/assets/54841342/a8774d17-8a83-4180-b007-07fec22e326e
