### ISSUE TITLE
Populate the lists from a rest call

### ISSUE THREAD

**Issue by dan-ward** [microsoft/azure-devops-extension-cascading-picklist#20]
It would be great to be able to populate the lists via a rest call, so we could always have up to date lists.

**Comment by danhellem** [comment]
Unfortunately this is an extension and not part of the core product. You can certainly make REST calls to get the entire list of values in a picklist.

**Comment by dan-ward** [comment]
Just want to confirm I'm following you, is there a way to do a rest call to populate the cascading picklist, or are you saying just for a normal picklist.  The use case is I have a CRM system that we pull our customers from and based on the customer I want a list of the custom products they have.  So parent picklist is Customer and child(cascaded pick list) is product.
