### ISSUE TITLE
Question about the data storage

### ISSUE THREAD

**Issue by cwelde** [microsoft/azure-devops-extension-cascading-picklist#24]
Reading through the code, I noticed that you guys use the Microsoft Extension Data Storage to store these notes, using a mix of the API and the SDK to save, get, and set them. (is that right?). https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops

I had a question on the data storage. Is there a limit to how much data can be stored in there? What if our cascading list (theoretically) grows very large? Why do you guys use a mix of the API and the SDK? Why not just one over the other?

**Comment by danhellem** [comment]
@navneet-g can you answer this one? I assume it is because the sdk does not contain all the API's available and that is why the mix of them both

**Comment by danhellem** [comment]
@cwelde this is most likely because we are using a preview API that is not yet in the SDK.

I am sure there is a storage limit. I don't know what it is off-hand...sorry :(

**Comment by edamon** [comment]
@danhellem @navneet-g I'd like an answer to this question too please.  ;)
