### ISSUE TITLE
Empty the pick list options upon changing the parent field

### ISSUE THREAD

**Issue by aksh-h** [microsoft/azure-devops-extension-cascading-picklist#31]
I managed to have 3 fields for cascading pick list extension, I'm having a trouble in clearing the pick list options. Let's say, there are 3 fields. I changed 1st field value, second field value got changed and the pick list options got refreshed- this is expected. But for 3rd field field value and options are still there - which should be refreshed (field and options should be empty). 

Is this possible to fix quickly?

**Comment by ByAgenT** [comment]
@aksh-h, if you want to remove all values from a field depending on the option of another value, you could use the following setup. 

Let's assume that you have two picklist fields - Field1 and Field2. When Field1 value is Value1 you need to show all the possible options for the Field2, but when Field1 value is set to Value2, you would want to clear Field2 value and remove all the possible values from it. Following example should help you solve that:

```json
{
  "version": 1,
  "cascades": {
      "Custom.Field1": {
          "Value1": {
              "Custom.Field2": "all"
          },
          "Value2": {
              "Custom.Field2": []
          }
      }
  }
}
```

**Comment by aksh-h** [comment]
@ByAgenT thank you. This will work only if we have few set of values. Adding empty array for each value doesn't work for me, because i have 300+ values at 3 levels.
Can you suggest me how can we achieve it in the code level.
Thanks.

**Comment by ByAgenT** [comment]
@aksh-h Since the extension is open sourced you are free to fork it and adapt to suit your organization needs. You could also create a script that will help you generate manifest for an extension, in this case [Azure DevOps API](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1) could be really handy!
