### ISSUE TITLE
Are cascading lists between three fields supported

### ISSUE THREAD

**Issue by Declanco** [microsoft/azure-devops-extension-cascading-picklist#32]
Are cascading lists between three fields supported? In the example below, the Service Teams and RequestType fields cascade as expected. But the third field, RequestSubType displays all the values: 

{
  "version": "1.0",
  "cascades": {
    "Custom.ServiceTeam": {
      "Service Team 1": {
        "Custom.RequestType": [
          "Blue.ServiceA",
          "Blue.ServiceB",
          "Blue.ServiceC"
        ]
      },
      "Service Team 2": {
        "Custom.RequestType": [
          "Red.Service1",
          "Red.Service2",
          "Red.Service3"
        ]
      }
    },
    "Custom.RequestType": {
      "Blue.ServiceA": {
        "Custom.RequestSubType": [
          "List A",
          "List B",
          "List C"
        ]
      },
      "Custom.RequestType": {
        "Red.Service1": {
          "Custom.RequestSubType": [
            "List 1",
            "List 2",
            "List 3"
          ]
        }
      }
    }
}

**Comment by ByAgenT** [comment]
@Declanco, yes, they should be supported, if I correctly understood your question. I found errors in your config, so I changed it to make it work.

Assuming that you will have this config:
```json
{
    "version": "1.0",
    "cascades": {
        "Custom.ServiceTeam": {
            "Service Team 1": {
                "Custom.RequestType": [
                    "Blue.ServiceA",
                    "Blue.ServiceB",
                    "Blue.ServiceC"
                ]
            },
            "Service Team 2": {
                "Custom.RequestType": [
                    "Red.Service1",
                    "Red.Service2",
                    "Red.Service3"
                ]
            }
        },
        "Custom.RequestType": {
            "Blue.ServiceA": {
                "Custom.RequestSubType": [
                    "List A",
                    "List B",
                    "List C"
                ]
            },
            "Red.Service1": {
                "Custom.RequestSubType": [
                    "List 1",
                    "List 2",
                    "List 3"
                ]
            }
        }
    }
}
```  

You will be able to get the following cascade for your fields
![image](https://user-images.githubusercontent.com/3288532/68547805-f5dd9880-03f6-11ea-848a-d371feaeb22c.png)
![image](https://user-images.githubusercontent.com/3288532/68547812-0a219580-03f7-11ea-823f-c820b1c48e21.png)

Please, let me know if this helps you.

**Comment by Declanco** [comment]
@ByAgenT 
I removed everything from the cascade file and pasted in the config above. Unfortunately, I still get the same issue
![image](https://user-images.githubusercontent.com/57536679/68632454-722db580-04a3-11ea-997f-f41fb1275b8a.png)

**Comment by ByAgenT** [comment]
@Declanco 
Could you please share your configuration?
What browser do you have?
Which version and edition of Azure DevOps do you use? (Azure DevOps Service or Azure DevOps Server)
Do you see any errors in the developer tools in your browser when you open the work item form page?

**Comment by ssteiner1** [comment]
I have the same issue;  we have 3 picklist fields, "Product", "Component" and "Module".   Using the extension, Component list will change depending on Product chosen, just can't get Module to change depending on Component chosen.  Attached is config.  I am in Chrome, Version 79.0.3945.117 (Official Build) (64-bit), and we use Azure DevOps Server.  I am unsure of the version on that though.  Any assistance is appreciated, thanks!
[CascadingListsConfig.txt](https://github.com/microsoft/azure-devops-extension-cascading-picklist/files/4060122/CascadingListsConfig.txt)

**Comment by Declanco** [comment]
@ByAgenT Thanks for you help on this, I finally got it to work using your example above and  a new Work Item (I think the original one may have been corrupt).

**Comment by shawndon-msft** [comment]
I am trying to do something similar but the list items in my RequestSubType overlap such that is could be List 1, List 3, List B. Depending on what Service Team they select.
