### ISSUE TITLE
Can I control a picklist based off of two fields?

### ISSUE THREAD

**Issue by taylordgordon** [microsoft/azure-devops-extension-cascading-picklist#35]
Great feature!

Is it possible to structure JSON in a way that would control a field's lookup options based off the values of two fields?

For example if I have 3 fields: ProductLine, RequestCategory, RequestType.  Can I get different lists of RequestTypes based on both the ProductLine and RequestCategory values?

If not, could you suggest where in the code would have to change to support that?  Happy to give it a try and submit a PR if it would help.  But not being a javascript expert some guidance would be great.

Thanks!

**Comment by taylordgordon** [comment]
cc @ByAgenT

**Comment by ByAgenT** [comment]
Hey @taylordgordon. Two separate fields could affect third field and options will be determined based on the intersection of choices for the two fields.

Here's an example:
```json
{
  "version": "1.0",
  "cascades": {
    "Custom.DeviceType": {
      "Laptop": {
        "Custom.DeviceVendor": [
          "Apple",
          "Microsoft"
        ],
        "Custom.DeviceName": [
          "MacBook",
          "Surface"
        ]
      },
      "Mobile": {
        "Custom.DeviceVendor": [
          "Apple",
          "Google"
        ],
        "Custom.DeviceName": [
          "Google Pixel",
          "iPhone"
        ]
      },
      "Wearable": {
        "Custom.DeviceVendor": [
          "Apple",
          "Google"
        ],
        "Custom.DeviceName": [
          "Fitbit",
          "Apple Watch"
        ]
      },
      "": {
        "Custom.DeviceVendor": "all",
        "Custom.DeviceName": "all"
      }
    },
    "Custom.DeviceVendor": {
      "Apple": {
        "Custom.DeviceName": [
          "MacBook",
          "Apple Watch",
          "iPhone"
        ]
      },
      "Microsoft": {
        "Custom.DeviceName": [
          "Surface"
        ]
      },
      "Google": {
        "Custom.DeviceName": [
          "Google Pixel",
          "Fitbit"
        ]
      },
      "": {
        "Custom.DeviceName": "all"
      }
    }
  }
}
```

This example creates a cascading options around the idea of devices. By default, full set of devices is available, see 
![image](https://user-images.githubusercontent.com/3288532/70388946-c0ae7100-19c9-11ea-93be-cdd5ee271e5e.png)
If we select Laptop as a device type, we will get vendors and devices filtered up:
![image](https://user-images.githubusercontent.com/3288532/70388953-e8053e00-19c9-11ea-8d24-0e7933795390.png)
![image](https://user-images.githubusercontent.com/3288532/70388955-ef2c4c00-19c9-11ea-904a-5041f06c0159.png)

And finally, if we would want to filter down names not only by type, but for the vendor as well, we select necessary vendor and get the result 
![image](https://user-images.githubusercontent.com/3288532/70388960-1256fb80-19ca-11ea-9736-2ffe55c4ae02.png)

Hope this example will help you. 
If you would like to extend the idea to suit your needs, you could look into [this file](https://github.com/microsoft/azure-devops-extension-cascading-picklist/blob/master/src/common/cascading.service.ts#L125) that is responsible for calculating field values of a cascades. Also, you could use this [reference](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops) to install modified extension for your organization.

**Comment by taylordgordon** [comment]
@ByAgenT - thanks much!  Really appreciate your response and this extension.  Extremely helpful.  Have a good one!

**Comment by Declanco** [comment]
Sorry for the delay, thanks for responding and supplying the example. Works perfectly!
