### ISSUE TITLE
Extension fails to load in TFS 2018.2 on-premise 

### ISSUE THREAD

**Issue by HakX91** [microsoft/azure-devops-extension-cascading-picklist#38]
1. Installed the extension on the server and navigated to  Cascading List tab.
![image](https://user-images.githubusercontent.com/25849893/72096598-872e9580-32e8-11ea-86ab-b518b6773015.png)
2. Opened chrom dev tools to see the console log
![image](https://user-images.githubusercontent.com/25849893/72097888-5e5bcf80-32eb-11ea-8803-b56033ef1c6d.png)
3. Tried on Chrome, IR, Edge and Firefox - fails in each browser

**Comment by ByAgenT** [comment]
Hey @HakX91. Unfortunately, this extension does not work on Azure DevOps Server of any on-prem TFS instances.

**Comment by vadim-kovalyov** [comment]
Thank you for reporting this issue, @HakX91 . As @ByAgenT mentioned above, the extension does not work on Azure DevOps Server. We are going to correct the description on the marketplace page to remove Server as a supported platform. Sorry for the confusion.
