### ISSUE TITLE
Can I control two fields based off the picklist selection of another?

### ISSUE THREAD

**Issue by jakeb444** [microsoft/azure-devops-extension-cascading-picklist#39]
Thanks - I love this feature! Is it possible to control the lookup options for two fields based on the value selected in another field? For example, I have 3 fields: CustomMake, CustomModel, and CustomColor. I would like to control the picklist options of CustomModel and CustomColor based on the value selected in CustomMake.

I'm very new to JSON (like started yesterday) and gave it a try below, but couldn't get it to work. Is this supported?

{
  "version": "1.0",
  "cascades": {
    "Custom.Make": {
      "Ford": {
        "Custom.Model": [
          "F-150",
          "Mustang"
        ],
        "Custom.Color": [
          "Red",
          "Blue"
		]
	  },
      "Dodge": {
        "Custom.Model": [
          "RAM",
          "Viper"
        ],
        "Custom.Color": [
          "Green",
          "Black"
		]
      }
    }
  }
}

Thanks!

**Comment by ByAgenT** [comment]
I suppose you are looking for this https://github.com/microsoft/azure-devops-extension-cascading-picklist/issues/35

**Comment by jakeb444** [comment]
Hi @ByAgenT. No, that's kind of the opposite of what I want to do. #35 is filtering the list in one field by the values in two other fields. (By the way, Taylor is my colleague and we got #35 working with your help. Thanks!)

I want to filter the lists in two fields by the value in one other field.

**Comment by ByAgenT** [comment]
Hi @jakeb444. #35 is covering both cases. If you will take a look at this example again, you may see, that when you select device type to laptop, vendor field will be filtered to show only laptop vendors and device name field will be filtered to show only laptop names.

As far as I can see, your JSON is valid. I've tried to reproduce your example.
Config:
```json
{
    "version": "1.0",
    "cascades": {
        "Custom.Make": {
            "Ford": {
                "Custom.Model": [
                    "F-150",
                    "Mustang"
                ],
                "Custom.Color": [
                    "Red",
                    "Blue"
                ]
            },
            "Dodge": {
                "Custom.Model": [
                    "RAM",
                    "Viper"
                ],
                "Custom.Color": [
                    "Green",
                    "Black"
                ]
            }
        }
    }
}
```
Initial state of fields:
![image](https://user-images.githubusercontent.com/3288532/73352004-3aaff780-42a1-11ea-82c8-1ab441eb573a.png)
![image](https://user-images.githubusercontent.com/3288532/73352032-4ac7d700-42a1-11ea-94f8-0ac8df2a15c1.png)

After setting value in one field, two fields are altered:
![image](https://user-images.githubusercontent.com/3288532/73352051-54e9d580-42a1-11ea-868b-d8834202694c.png)
![image](https://user-images.githubusercontent.com/3288532/73352068-603d0100-42a1-11ea-86b9-91f1acbc8809.png)

I hope this clarifies configuration to you. If I misunderstood your question, let me know.

**Comment by jakeb444** [comment]
Yes, this works as you described. Thanks for your help!
