### ISSUE TITLE
Getting error - this.workItemService.filterAllowedFieldValues is not a function

### ISSUE THREAD

**Issue by iyadnaim** [microsoft/azure-devops-extension-cascading-picklist#43]
I am trying to use this extension on-promise, I have replicated the exact steps to run, however, I got the below error, I am using the latest Azure DevOps Server Version Dev17.M153.5

Uncaught (in promise) TypeError: this.workItemService.filterAllowedFieldValues is not a function
    at e.<anonymous> (cascading.service.ts:137)
    at global.js:20
    at Object.next (global.js:20)
    at global.js:20
    at new Promise (<anonymous>)
    at n (global.js:20)
    at cascading.service.ts:136
    at Array.map (<anonymous>)
    at e.<anonymous> (cascading.service.ts:136)
    at global.js:20

Please help!

**Comment by danhellem** [comment]
I am guessing this API is not available yet on server. I will need to update the documentation so that folks are not confused
