### ISSUE TITLE
example isn't work in Azure Devops Server 2019

### ISSUE THREAD

**Issue by twomoonbrew** [microsoft/azure-devops-extension-cascading-picklist#44]
Hi -
I'm trying to get the example working on our installation of Azure DevOps.  

Working on our Bug types:

Created new picklist (string) field named "MajorRelease" (no spaces) with values "Release Blue" and "Release Red"

![cascading-sheet-major-rel](https://user-images.githubusercontent.com/8784147/78050233-d658f500-7330-11ea-9442-c608ac989a75.png)

Created another picklist (string) field named "MinorRelease" (no spaces) with values "Blue.1", "Blue.2", "Blue.3", "Red.A", "Red.B" and "Red.C".

![cascading-sheet-minor-rel](https://user-images.githubusercontent.com/8784147/78050168-c0e3cb00-7330-11ea-83a1-a67a1d7e595b.png)
Pasted the sample JSON into the Cascading Lists Config for our project settings, and saved the configuration.

Opened a new window, created a new bug, and i can see the two new fields.    Under Major Release, I select "Release Blue", and then under Minor Release, i expect to only see the Blue items listed, but instead I see all 6 items (red and blue).

![cascading-sheet-not-working](https://user-images.githubusercontent.com/8784147/78049758-49ae3700-7330-11ea-8e49-897d1bc81fe5.png)

**Comment by danhellem** [comment]
Can you please validate to make sure the field name is in fact custom.majorrelease? You may need to use the REST API's to do so. Do you get any kind of error in the dev console?

**Comment by miltonvid2205** [comment]
Did this issue get resolved. I am still facing the issue
