### ISSUE TITLE
incorrect work on board

### ISSUE THREAD

**Issue by w0nders** [microsoft/azure-devops-extension-cascading-picklist#48]
I linked custom filed (example Status) with work item state, but work isn't correct (i can move anywhere work items).
General task - restrict change state
My config (example):
"ToDo": {
"Custom.Status": [
"ToDo"
]
},
"In progress": {
"Custom.Status": [
"Puse",
"Analytic",
"Dev",
"Other"
]
},

**Comment by danhellem** [comment]
Not sure I understand the question. Are you saying the JSON configuration is not working on the Custom.Status field?

The JSON should look something like this...

```
{
  "version": "1",
  "cascades": {
    "System.State": {
      "New": {
        "Custom.MyReasonField" : [
          "New Bug",
          "Not Fixed"
        ]
      },
      "Active": {
        "Custom.MyReasonField" : [
          "Approved",
          "Investigate",
          "Reactivated"
        ]
      },
      "Resolved": {
        "Custom.MyReasonField": [
          "Fixed",
          "As Designed",
          "Cannot Reproduce",
          "Not Going to Fix",
          "Resolved in Error"
        ]
      },
      "Closed": {
        "Custom.MyReasonField": [
          "Verified"
        ]
      }
    }
  }
}
```

**Comment by w0nders** [comment]
it seems not correctly work on Boards (my custom filed "status" on work
item linked to System.State)


чт, 25 июн. 2020 г. в 18:14, Dan Hellem <notifications@github.com>:
