### ISSUE TITLE
Cascading List

### ISSUE THREAD

**Issue by fred1n** [microsoft/azure-devops-extension-cascading-picklist#50]
Installed the extension but I don't see the Cascading List option from anywhere on my project or account.  Where exactly is the Cascading List supposed to show up?

**Comment by bz-wow** [comment]
In the project setting page, at the bottom, you'll find "Extensions - Cascading Lists".

**Comment by caio-ody** [comment]
Same issue here. Installed the extension, and still can't see it in the project settings page.
Signed out/in again, still can't see it.

**Comment by AminTi** [comment]
If the problem persists, please inform me, and I'll assist you further.
