### ISSUE TITLE
Not working - Options Disappearing

### ISSUE THREAD

**Issue by teresa52729** [microsoft/azure-devops-extension-cascading-picklist#78]
I was able to install and configure the cascading list extension but it does not seem to work. I first based the second picklist on the System.State field value and then I tried it based on a custom field value. Neither of them worked. Here is the config file for the one using the custom field.

The Custom.059c9d15-c6e7-4ec9-8015-9f5cb685bfa2 is defined as a picklist with Test1, Test2, Test3, and Test4 as its values.

If I test it multiple times, the cascading picklist values will disappear altogether. 

{
“version”: “1”,
“cascades”: {
“Custom.HideStatePicklist”: {
“New”: {
“Custom.059c9d15-c6e7-4ec9-8015-9f5cb685bfa2”: [
“Test1”
]
},
“Active”: {
“Custom.059c9d15-c6e7-4ec9-8015-9f5cb685bfa2”: [
“Test2”
]
},
“Resolved”: {
“Custom.059c9d15-c6e7-4ec9-8015-9f5cb685bfa2”: [
“Test3”
]
},
“Closed”: {
“Custom.059c9d15-c6e7-4ec9-8015-9f5cb685bfa2”: [
“Test3”
]
}
}
}
}

**Comment by raydixon** [comment]
@teresa52729 do you have [New Boards Hubs](https://devblogs.microsoft.com/devops/azure-boards-ux-modernization-public-preview/) enabled in [Preview Features](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops)? If so, try turning it off and see if the Cascading Picklist extension starts working, again.

I had a project in which I recently set up Cascading Picklist and it stopped working shortly after I set it up. I noticed that New Boards Hub was enabled, so I tried turning it off and as soon as I did, Cascading Picklist started working, again.

**Comment by AminTi** [comment]
Hi i just tried it it works as expected
