### ISSUE TITLE
Functionality of cascading lists is disrupted by the New Boards Hubs public preview

### ISSUE THREAD

**Issue by d-w-huang** [microsoft/azure-devops-extension-cascading-picklist#81]
We are using [ADO extension Cascading Lists](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.cascading-picklists-extension&targetId=8db89e80-e21c-40af-85f8-716193a9e239&utm_source=vstsproduct&utm_medium=ExtHubManageList) for displaying field options controlled by another field. It was working well until recent UI upgrades of ADO. All options would be displayed regardless what was picked in control field.

After some discussion and research, we found out that [New Boards Hubs public preview](https://docs.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-202-update#new-boards-hubs-now-available-in-public-preview) might be impacting some ADO extensions. Once we turned it off from preview features, this extension for Cascading Lists was back to normal behaviors.

Hopefully, the issue or conflict between New Boards Hubs and this extension Cascading Lists can be resolved soon so that we won't miss experience of new functionalities of ADO.

**Comment by danhellem** [comment]
@d-w-huang  can you please re-test this and log some screen shots if it is still an issue.

**Comment by MOlausson** [comment]
@d-w-huang is this still an issue?

**Comment by MOlausson** [comment]
Closing issue due to lack of feedback. @d-w-huang feel free to reopen and provide your current status.

**Comment by AminTi** [comment]
Thanks for reporting, we'll dig into this again.
